server.port=8083
server.servlet.context-path=/api/admin
spring.application.name=admin-service

# Database (Separate DB for Admin logs/feedback)
spring.datasource.url=jdbc:sqlite:adminDatabase.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# External Services (To fetch data for reports)
service.passenger.url=http://localhost:8081/api/passenger-profile
service.payment.url=http://localhost:8082/api/payment